### ISSUE TITLE
query id has different variable name

### ISSUE THREAD

**Issue by SophMC** [tomkdickinson/Instagram-Search-API-Python#7]
Hello,

I was having trouble with getting the correct (or in some case any) query_ids from:
`def get_query_id(self, doc)`

The query id was no longer to be found in c="", it can now be found in queryId:""
so just need to change line 177
`for query_id in re.findall("(?<=c=\")[0-9]{1,}", text)` 
to
`for query_id in re.findall("(?<queryId:\")[0-9]{1,}", text)`

Once I change this everything worked again and I haven't had a:
`ERROR:root:Could not extract Query Id, exiting`

Soph

**Comment by roberterdin** [comment]
see #6 :)

**Comment by tomkdickinson** [comment]
This should be fixed now. Found out QueryID also is also alphanumeric now.
